# Generated by Django 4.2.3 on 2023-07-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_plan', '0002_task_technician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
