# Generated by Django 4.2.3 on 2023-07-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('OPERATOR', 'Operator')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
