# Generated by Django 4.2.3 on 2023-07-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_delete_equipmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(default='1', verbose_name='Year of Manufacture'),
            preserve_default=False,
        ),
    ]
