# Generated by Django 4.2.3 on 2023-07-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_year_of_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Manufacture'),
        ),
    ]
